// This file is automatically generated. Do not edit it directly.
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs';
import type { Database } from '@/integrations/supabase/types';

export const supabase = createClientComponentClient<Database>();